table listings
	lineageTag: 8aa2163a-ca70-40a5-b399-8743391b4720

	measure 'Price per listing' = SUM(listings[price])/DISTINCTCOUNT(listings[id])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: f517237e-079e-487a-8bbd-ce8fa7d83d42

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Avg Annual Revenue' = SUM(listings[price])*365*[% occupied]/DISTINCTCOUNT(listings[id])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 26831f3a-cf96-480d-b43c-cf13ae7d746a

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column id
		dataType: int64
		formatString: 0
		lineageTag: 39c2743c-4147-4995-b4f7-2033dc5f9493
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column listing_url
		dataType: string
		lineageTag: e3445994-6571-4067-8e64-9090cccef052
		summarizeBy: none
		sourceColumn: listing_url

		annotation SummarizationSetBy = Automatic

	column scrape_id
		dataType: double
		lineageTag: 96fc52f2-91b6-465e-8c86-8dc51d6288ed
		summarizeBy: sum
		sourceColumn: scrape_id

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column last_scraped
		dataType: dateTime
		formatString: Long Date
		lineageTag: cd1c3087-7950-4871-8759-2143f7fca869
		summarizeBy: none
		sourceColumn: last_scraped

		variation Variation
			isDefault
			relationship: 938ddd4b-6ef9-496f-a083-e3c616588d09
			defaultHierarchy: LocalDateTable_25608900-bce3-4047-844b-7aea6ef49c9f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column name
		dataType: string
		lineageTag: d75eba64-58b3-48a1-890d-c4198a8fa34b
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column summary
		dataType: string
		lineageTag: f45a7bbb-4406-493a-bc2c-988d27063d02
		summarizeBy: none
		sourceColumn: summary

		annotation SummarizationSetBy = Automatic

	column space
		dataType: string
		lineageTag: 8f3a7a3e-35f6-48a7-acaa-8bd88e83c96e
		summarizeBy: none
		sourceColumn: space

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: 7714a6af-bd7e-4f5d-88af-56a50ee97299
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column experiences_offered
		dataType: string
		lineageTag: 714de995-762f-4944-a7db-96882f4786d9
		summarizeBy: none
		sourceColumn: experiences_offered

		annotation SummarizationSetBy = Automatic

	column neighborhood_overview
		dataType: string
		lineageTag: 6836be8b-7e6b-43ee-bb97-ba5e2957861c
		summarizeBy: none
		sourceColumn: neighborhood_overview

		annotation SummarizationSetBy = Automatic

	column notes
		dataType: string
		lineageTag: a074399a-ea68-491a-a738-4a81d4343160
		summarizeBy: none
		sourceColumn: notes

		annotation SummarizationSetBy = Automatic

	column transit
		dataType: string
		lineageTag: d25a4cb1-a745-4e50-8260-898de08d612c
		summarizeBy: none
		sourceColumn: transit

		annotation SummarizationSetBy = Automatic

	column thumbnail_url
		dataType: string
		lineageTag: 3029b4f2-4089-4269-a321-4a62c1e857f8
		summarizeBy: none
		sourceColumn: thumbnail_url

		annotation SummarizationSetBy = Automatic

	column medium_url
		dataType: string
		lineageTag: d55e345d-517c-4218-9284-f18c520ce1c9
		summarizeBy: none
		sourceColumn: medium_url

		annotation SummarizationSetBy = Automatic

	column picture_url
		dataType: string
		lineageTag: 81d26ef6-cb07-436e-ad56-f47a867305f1
		summarizeBy: none
		sourceColumn: picture_url

		annotation SummarizationSetBy = Automatic

	column xl_picture_url
		dataType: string
		lineageTag: 63b0a7d5-2de3-4fb6-bc66-a522bea71f2f
		summarizeBy: none
		sourceColumn: xl_picture_url

		annotation SummarizationSetBy = Automatic

	column host_id
		dataType: int64
		formatString: 0
		lineageTag: 2a0c8f0c-ee99-4a1f-a22f-5f6f02b040f3
		summarizeBy: sum
		sourceColumn: host_id

		annotation SummarizationSetBy = Automatic

	column host_url
		dataType: string
		lineageTag: be9ddfaf-43b7-4763-88b9-f0bbe2dc4ecd
		summarizeBy: none
		sourceColumn: host_url

		annotation SummarizationSetBy = Automatic

	column host_name
		dataType: string
		lineageTag: a4c9e52c-61ee-413f-96ab-1f46d2bda855
		summarizeBy: none
		sourceColumn: host_name

		annotation SummarizationSetBy = Automatic

	column host_since
		dataType: dateTime
		formatString: Long Date
		lineageTag: df49344c-8109-4a19-b0b1-387617843808
		summarizeBy: none
		sourceColumn: host_since

		variation Variation
			isDefault
			relationship: 080b113f-f2b9-49b7-9ebb-76f613968f10
			defaultHierarchy: LocalDateTable_d987202e-0c55-4b72-b4a6-6e4acd5114c1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column host_location
		dataType: string
		lineageTag: 5f20f0e0-b5a4-4085-bf44-2460ed3e9982
		summarizeBy: none
		sourceColumn: host_location

		annotation SummarizationSetBy = Automatic

	column host_about
		dataType: string
		lineageTag: 4ec9d1f8-6f72-4c61-835e-53b28c457722
		summarizeBy: none
		sourceColumn: host_about

		annotation SummarizationSetBy = Automatic

	column host_response_time
		dataType: string
		lineageTag: 902cc162-901a-4c1a-8c06-a3754895614f
		summarizeBy: none
		sourceColumn: host_response_time

		annotation SummarizationSetBy = Automatic

	column host_response_rate
		dataType: string
		lineageTag: 3066abd8-6203-416d-8d81-0d0bdcfb8451
		summarizeBy: none
		sourceColumn: host_response_rate

		annotation SummarizationSetBy = Automatic

	column host_acceptance_rate
		dataType: string
		lineageTag: 0f32d4ef-344c-4dcf-918d-d7b4d69a8eb7
		summarizeBy: none
		sourceColumn: host_acceptance_rate

		annotation SummarizationSetBy = Automatic

	column host_is_superhost
		dataType: string
		lineageTag: d4dee8d5-5b90-441d-a573-513536910e7b
		summarizeBy: none
		sourceColumn: host_is_superhost

		annotation SummarizationSetBy = Automatic

	column host_thumbnail_url
		dataType: string
		lineageTag: 4176ebe7-8c53-4832-a948-2090b4590562
		summarizeBy: none
		sourceColumn: host_thumbnail_url

		annotation SummarizationSetBy = Automatic

	column host_picture_url
		dataType: string
		lineageTag: 33bea367-2653-4009-8b94-cf4833752eee
		summarizeBy: none
		sourceColumn: host_picture_url

		annotation SummarizationSetBy = Automatic

	column host_neighbourhood
		dataType: string
		lineageTag: 90f945fa-3b5e-46eb-92bc-ea942cb569bb
		summarizeBy: none
		sourceColumn: host_neighbourhood

		annotation SummarizationSetBy = Automatic

	column host_listings_count
		dataType: int64
		formatString: 0
		lineageTag: 672a4e77-3092-4060-9d2d-328007a42c1a
		summarizeBy: sum
		sourceColumn: host_listings_count

		annotation SummarizationSetBy = Automatic

	column host_total_listings_count
		dataType: int64
		formatString: 0
		lineageTag: 01d2bf10-8247-4cb2-976d-b18c2508197f
		summarizeBy: sum
		sourceColumn: host_total_listings_count

		annotation SummarizationSetBy = Automatic

	column host_verifications
		dataType: string
		lineageTag: 1c349afe-c075-464b-816e-e7522d55a0d9
		summarizeBy: none
		sourceColumn: host_verifications

		annotation SummarizationSetBy = Automatic

	column host_has_profile_pic
		dataType: string
		lineageTag: 73bdb567-6c1b-45c2-b5e3-d8aa3aab27b5
		summarizeBy: none
		sourceColumn: host_has_profile_pic

		annotation SummarizationSetBy = Automatic

	column host_identity_verified
		dataType: string
		lineageTag: 18c9afb1-80cb-4edc-ad23-f88cfb6e21f1
		summarizeBy: none
		sourceColumn: host_identity_verified

		annotation SummarizationSetBy = Automatic

	column street
		dataType: string
		lineageTag: 66c1b020-0998-4d4a-b33a-a669b1b9f17f
		summarizeBy: none
		sourceColumn: street

		annotation SummarizationSetBy = Automatic

	column neighbourhood
		dataType: string
		lineageTag: 735015e9-becc-4850-9ebc-afb6d6656ca2
		summarizeBy: none
		sourceColumn: neighbourhood

		annotation SummarizationSetBy = Automatic

	column neighbourhood_cleansed
		dataType: string
		lineageTag: ffc51057-085d-4546-91dc-48b34015fbae
		summarizeBy: none
		sourceColumn: neighbourhood_cleansed

		annotation SummarizationSetBy = Automatic

	column neighbourhood_group_cleansed
		dataType: string
		lineageTag: 35d64cc7-555f-49b8-a1fa-31dc8d03ff14
		summarizeBy: none
		sourceColumn: neighbourhood_group_cleansed

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: f0097080-06f5-4185-bb19-2af87551d340
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: 40c034fc-b69a-42f9-8861-85364c583015
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column zipcode
		dataType: int64
		formatString: 0
		lineageTag: 0355ec2d-d977-48a5-ac14-c5685f353d4c
		summarizeBy: sum
		sourceColumn: zipcode

		annotation SummarizationSetBy = Automatic

	column market
		dataType: string
		lineageTag: e526554a-739b-4ec4-b747-988299407023
		summarizeBy: none
		sourceColumn: market

		annotation SummarizationSetBy = Automatic

	column smart_location
		dataType: string
		lineageTag: d6872c43-7222-4fd0-9eaf-1233d3e5c851
		summarizeBy: none
		sourceColumn: smart_location

		annotation SummarizationSetBy = Automatic

	column country_code
		dataType: string
		lineageTag: b324005e-bdbe-4cd1-a55c-1e548b487392
		summarizeBy: none
		sourceColumn: country_code

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: 77e62fc4-662b-47d9-beb5-ab49c27d538e
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		lineageTag: 6f2d94b8-8a5c-47c3-88d7-d13e072b8725
		summarizeBy: sum
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column longitude
		dataType: double
		lineageTag: 265635cc-233e-4790-8bdb-b9db24c8dc0e
		summarizeBy: sum
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column is_location_exact
		dataType: string
		lineageTag: ef0d383c-9bf0-432e-9a01-15244f39860c
		summarizeBy: none
		sourceColumn: is_location_exact

		annotation SummarizationSetBy = Automatic

	column property_type
		dataType: string
		lineageTag: 4dfdaafe-327f-40f1-9255-32d31374e90e
		summarizeBy: none
		sourceColumn: property_type

		annotation SummarizationSetBy = Automatic

	column room_type
		dataType: string
		lineageTag: 78cbe8d6-edb7-4866-8c35-8aff98843da8
		summarizeBy: none
		sourceColumn: room_type

		annotation SummarizationSetBy = Automatic

	column accommodates
		dataType: int64
		formatString: 0
		lineageTag: bb943978-8c05-48cc-af51-0a8e56098e3e
		summarizeBy: sum
		sourceColumn: accommodates

		annotation SummarizationSetBy = Automatic

	column bathrooms
		dataType: double
		lineageTag: 2b812b0d-15d3-4bb0-bfb8-3e9da7cf68e4
		summarizeBy: sum
		sourceColumn: bathrooms

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column bedrooms
		dataType: int64
		formatString: 0
		lineageTag: 1be337b6-4b30-4a74-bb7b-7968d1e38aa8
		summarizeBy: sum
		sourceColumn: bedrooms

		annotation SummarizationSetBy = Automatic

	column beds
		dataType: int64
		formatString: 0
		lineageTag: 01efdde3-5b7a-4a5f-9731-9ea707c30941
		summarizeBy: sum
		sourceColumn: beds

		annotation SummarizationSetBy = Automatic

	column bed_type
		dataType: string
		lineageTag: f074b2b8-5480-4e35-99ad-5b97383d0c73
		summarizeBy: none
		sourceColumn: bed_type

		annotation SummarizationSetBy = Automatic

	column amenities
		dataType: string
		lineageTag: 34c00d98-f716-43bc-9059-e0c1a32ea462
		summarizeBy: none
		sourceColumn: amenities

		annotation SummarizationSetBy = Automatic

	column square_feet
		dataType: int64
		formatString: 0
		lineageTag: 3a14ef4a-290b-4e2b-82f5-c60887132622
		summarizeBy: sum
		sourceColumn: square_feet

		annotation SummarizationSetBy = Automatic

	column price
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 94ce9d98-b2b1-42c9-845f-591c4ce36284
		summarizeBy: sum
		sourceColumn: price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column weekly_price
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: b685daf2-706a-43c5-bd38-9ba6b16380b8
		summarizeBy: sum
		sourceColumn: weekly_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column monthly_price
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 604b7a25-22d5-4134-a931-99965395352c
		summarizeBy: sum
		sourceColumn: monthly_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column security_deposit
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 599383e4-85c6-46aa-bd2e-8ef1bc0ae82e
		summarizeBy: sum
		sourceColumn: security_deposit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column cleaning_fee
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 09dc2d6f-fe1a-444a-97d9-fb3d86e27e2a
		summarizeBy: sum
		sourceColumn: cleaning_fee

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column guests_included
		dataType: int64
		formatString: 0
		lineageTag: d0652978-4690-476d-a2c2-eac0f0302ee0
		summarizeBy: sum
		sourceColumn: guests_included

		annotation SummarizationSetBy = Automatic

	column extra_people
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 65d69a03-2fc7-437d-b31e-9efb2ab00566
		summarizeBy: sum
		sourceColumn: extra_people

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column minimum_nights
		dataType: int64
		formatString: 0
		lineageTag: c0b16366-eae2-4496-8f9a-2b76aa9aa82b
		summarizeBy: sum
		sourceColumn: minimum_nights

		annotation SummarizationSetBy = Automatic

	column maximum_nights
		dataType: int64
		formatString: 0
		lineageTag: a11abc30-566a-4627-8267-f0a91cea5feb
		summarizeBy: sum
		sourceColumn: maximum_nights

		annotation SummarizationSetBy = Automatic

	column calendar_updated
		dataType: string
		lineageTag: 7b1e505e-de6c-4978-bbf0-0fbdcb7faba9
		summarizeBy: none
		sourceColumn: calendar_updated

		annotation SummarizationSetBy = Automatic

	column has_availability
		dataType: string
		lineageTag: 81f85c88-e6c3-400b-808e-af261e6dcf8e
		summarizeBy: none
		sourceColumn: has_availability

		annotation SummarizationSetBy = Automatic

	column availability_30
		dataType: int64
		formatString: 0
		lineageTag: e5fe158c-02df-458c-96f2-160dc9441607
		summarizeBy: sum
		sourceColumn: availability_30

		annotation SummarizationSetBy = Automatic

	column availability_60
		dataType: int64
		formatString: 0
		lineageTag: d55a6dbf-c20a-4b06-80b1-b2a09d1a3867
		summarizeBy: sum
		sourceColumn: availability_60

		annotation SummarizationSetBy = Automatic

	column availability_90
		dataType: int64
		formatString: 0
		lineageTag: 19e06ce6-198e-41d4-8d6b-a6e13158a028
		summarizeBy: sum
		sourceColumn: availability_90

		annotation SummarizationSetBy = Automatic

	column availability_365
		dataType: int64
		formatString: 0
		lineageTag: 2ec15d20-feca-477a-bfab-93d50fa2c038
		summarizeBy: sum
		sourceColumn: availability_365

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"listings","TableItemName":"Annual Availablity","ObjectType":4},"LinkType":"UsedInGroup"}]

	column calendar_last_scraped
		dataType: dateTime
		formatString: Long Date
		lineageTag: bdc1e314-65fb-4052-872e-5f12dce332ad
		summarizeBy: none
		sourceColumn: calendar_last_scraped

		variation Variation
			isDefault
			relationship: c4c8cffe-43cd-4773-877d-928785b49493
			defaultHierarchy: LocalDateTable_702a8179-7787-4d62-8807-1a5744262c70.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column number_of_reviews
		dataType: int64
		formatString: 0
		lineageTag: 85b35144-b609-489b-91a5-9d2ae5aee465
		summarizeBy: sum
		sourceColumn: number_of_reviews

		annotation SummarizationSetBy = Automatic

	column first_review
		dataType: dateTime
		formatString: Long Date
		lineageTag: 24ef4b53-55a5-417e-8cfe-a5303c67b05a
		summarizeBy: none
		sourceColumn: first_review

		variation Variation
			isDefault
			relationship: 81661354-156d-4c2f-b778-f39f145281f0
			defaultHierarchy: LocalDateTable_678ebfbe-d266-4678-aca6-abaa75bb565c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column last_review
		dataType: dateTime
		formatString: Long Date
		lineageTag: 40c8b393-508b-4255-a5a0-d6d52399af21
		summarizeBy: none
		sourceColumn: last_review

		variation Variation
			isDefault
			relationship: 0e7e3620-94b5-477c-b3e5-74fe15065262
			defaultHierarchy: LocalDateTable_e207154e-312e-4c31-afbb-1dd667df44a2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column review_scores_rating
		dataType: int64
		formatString: 0
		lineageTag: 644cebe7-5b66-43ad-9be5-801dda022fe8
		summarizeBy: sum
		sourceColumn: review_scores_rating

		annotation SummarizationSetBy = Automatic

	column review_scores_accuracy
		dataType: int64
		formatString: 0
		lineageTag: 16ae6116-5433-499b-ad68-b3bc63cca2bc
		summarizeBy: sum
		sourceColumn: review_scores_accuracy

		annotation SummarizationSetBy = Automatic

	column review_scores_cleanliness
		dataType: int64
		formatString: 0
		lineageTag: 6915acd8-f050-4065-8132-d09c7c8151fd
		summarizeBy: sum
		sourceColumn: review_scores_cleanliness

		annotation SummarizationSetBy = Automatic

	column review_scores_checkin
		dataType: int64
		formatString: 0
		lineageTag: 49e858be-b3e7-436b-afd5-853e645ef6a7
		summarizeBy: sum
		sourceColumn: review_scores_checkin

		annotation SummarizationSetBy = Automatic

	column review_scores_communication
		dataType: int64
		formatString: 0
		lineageTag: e18b838c-d253-44dd-9002-39f1461b0901
		summarizeBy: sum
		sourceColumn: review_scores_communication

		annotation SummarizationSetBy = Automatic

	column review_scores_location
		dataType: int64
		formatString: 0
		lineageTag: 7951e101-ce86-4841-b146-7ab45045026e
		summarizeBy: sum
		sourceColumn: review_scores_location

		annotation SummarizationSetBy = Automatic

	column review_scores_value
		dataType: int64
		formatString: 0
		lineageTag: 0ed38bb6-25d4-4a3c-b00e-7ab79c093ca9
		summarizeBy: sum
		sourceColumn: review_scores_value

		annotation SummarizationSetBy = Automatic

	column requires_license
		dataType: string
		lineageTag: af7aeb26-cfe9-442c-b039-3c576c3753e6
		summarizeBy: none
		sourceColumn: requires_license

		annotation SummarizationSetBy = Automatic

	column license
		dataType: string
		lineageTag: bd013e67-9bc9-496c-8d10-f97be0ef7db3
		summarizeBy: none
		sourceColumn: license

		annotation SummarizationSetBy = Automatic

	column jurisdiction_names
		dataType: string
		lineageTag: 7b18b89c-260f-4a03-9069-804ecf925905
		summarizeBy: none
		sourceColumn: jurisdiction_names

		annotation SummarizationSetBy = Automatic

	column instant_bookable
		dataType: string
		lineageTag: 94df5b5a-5b33-430e-b795-393c9f2a0bc8
		summarizeBy: none
		sourceColumn: instant_bookable

		annotation SummarizationSetBy = Automatic

	column cancellation_policy
		dataType: string
		lineageTag: 184a988b-bd1a-46db-a626-01e49a33a532
		summarizeBy: none
		sourceColumn: cancellation_policy

		annotation SummarizationSetBy = Automatic

	column require_guest_profile_picture
		dataType: string
		lineageTag: 5c73118c-09c4-4025-8fdd-2b98b5680693
		summarizeBy: none
		sourceColumn: require_guest_profile_picture

		annotation SummarizationSetBy = Automatic

	column require_guest_phone_verification
		dataType: string
		lineageTag: ee7261c4-1c22-4750-bba7-650fe4dceed5
		summarizeBy: none
		sourceColumn: require_guest_phone_verification

		annotation SummarizationSetBy = Automatic

	column calculated_host_listings_count
		dataType: int64
		formatString: 0
		lineageTag: e29eb24e-e4e3-45c5-a908-f890029f507a
		summarizeBy: sum
		sourceColumn: calculated_host_listings_count

		annotation SummarizationSetBy = Automatic

	column reviews_per_month
		dataType: double
		lineageTag: 4d024361-6cba-4a6f-82af-3a5b27282c3c
		summarizeBy: sum
		sourceColumn: reviews_per_month

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column %Occupied = AVERAGE(listings[availability_365])/365
		lineageTag: 87cc3b47-1805-4425-9421-c6c9d4710b34
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Annual Availablity' =
			VAR __Count = 5
			
			VAR __Min = MIN('listings'[availability_365])
			
			VAR __Max = MAX('listings'[availability_365])
			
			VAR __Difference = (__Max - __Min)
			
			VAR __Size = IF(__Difference > 0, __Difference / __Count, 1)
			
			VAR __BinNumber = INT(('listings'[availability_365] - __Min) / __Size)
			
			RETURN
			  IF(
			    ISBLANK('listings'[availability_365]),
			    BLANK(),
			    __Min + (MIN(__BinNumber, __Count - 1) * __Size)
			  )
		formatString: 0
		lineageTag: 20d91cae-48ad-4fc8-97b3-5d290a804348
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "listings"
				          }
				        },
				        "Property": "availability_365"
				      }
				    }
				  ]
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"l","Entity":"listings"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"l"}},"Property":"availability_365"}}],"BinItem":{"Expression":{"Member":{"Expression":{"Discretize":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"l"}},"Property":"availability_365"}},"Count":5}},"Member":"Min"}}}}

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column Occupancy = IF(listings[Annual Availablity]=0,"292 - 365 days",if(listings[Annual Availablity]=73, "219 - 292 days", if(listings[Annual Availablity]=146, "146 - 219 days", if(listings[Annual Availablity]=219, "73 - 146 days", if(listings[Annual Availablity]=292, "0 - 73 days")))))
		lineageTag: e7fa9930-0d6a-4d4b-8fe8-bb71a9c0e5e9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition listings-30ae0b1c-2ca5-4544-b1ef-5804cc120708 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\sarinas\Desktop\OneDriveLocalBackup\Hackathon18\listings.csv"),[Delimiter=",", Columns=92, Encoding=1252, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"id", Int64.Type}, {"listing_url", type text}, {"scrape_id", type number}, {"last_scraped", type date}, {"name", type text}, {"summary", type text}, {"space", type text}, {"description", type text}, {"experiences_offered", type text}, {"neighborhood_overview", type text}, {"notes", type text}, {"transit", type text}, {"thumbnail_url", type text}, {"medium_url", type text}, {"picture_url", type text}, {"xl_picture_url", type text}, {"host_id", Int64.Type}, {"host_url", type text}, {"host_name", type text}, {"host_since", type date}, {"host_location", type text}, {"host_about", type text}, {"host_response_time", type text}, {"host_response_rate", type text}, {"host_acceptance_rate", type text}, {"host_is_superhost", type text}, {"host_thumbnail_url", type text}, {"host_picture_url", type text}, {"host_neighbourhood", type text}, {"host_listings_count", Int64.Type}, {"host_total_listings_count", Int64.Type}, {"host_verifications", type text}, {"host_has_profile_pic", type text}, {"host_identity_verified", type text}, {"street", type text}, {"neighbourhood", type text}, {"neighbourhood_cleansed", type text}, {"neighbourhood_group_cleansed", type text}, {"city", type text}, {"state", type text}, {"zipcode", Int64.Type}, {"market", type text}, {"smart_location", type text}, {"country_code", type text}, {"country", type text}, {"latitude", type number}, {"longitude", type number}, {"is_location_exact", type text}, {"property_type", type text}, {"room_type", type text}, {"accommodates", Int64.Type}, {"bathrooms", type number}, {"bedrooms", Int64.Type}, {"beds", Int64.Type}, {"bed_type", type text}, {"amenities", type text}, {"square_feet", Int64.Type}, {"price", Currency.Type}, {"weekly_price", Currency.Type}, {"monthly_price", Currency.Type}, {"security_deposit", Currency.Type}, {"cleaning_fee", Currency.Type}, {"guests_included", Int64.Type}, {"extra_people", Currency.Type}, {"minimum_nights", Int64.Type}, {"maximum_nights", Int64.Type}, {"calendar_updated", type text}, {"has_availability", type text}, {"availability_30", Int64.Type}, {"availability_60", Int64.Type}, {"availability_90", Int64.Type}, {"availability_365", Int64.Type}, {"calendar_last_scraped", type date}, {"number_of_reviews", Int64.Type}, {"first_review", type date}, {"last_review", type date}, {"review_scores_rating", Int64.Type}, {"review_scores_accuracy", Int64.Type}, {"review_scores_cleanliness", Int64.Type}, {"review_scores_checkin", Int64.Type}, {"review_scores_communication", Int64.Type}, {"review_scores_location", Int64.Type}, {"review_scores_value", Int64.Type}, {"requires_license", type text}, {"license", type text}, {"jurisdiction_names", type text}, {"instant_bookable", type text}, {"cancellation_policy", type text}, {"require_guest_profile_picture", type text}, {"require_guest_phone_verification", type text}, {"calculated_host_listings_count", Int64.Type}, {"reviews_per_month", type number}}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type", {"zipcode"})
				in
				    #"Removed Errors"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

