table occupancy
	lineageTag: ccc3b51a-d410-4099-94a3-2b5d16b54126

	measure '% occupied' = CALCULATE(Count('occupancy'[available]),'occupancy'[available]="t")/COUNT('occupancy'[available])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e0ce3e9b-2521-49fc-9d09-8df805117418

	column listing_id
		dataType: int64
		formatString: 0
		lineageTag: 3867c004-7ccf-4a14-a678-ea462697b06b
		summarizeBy: none
		sourceColumn: listing_id

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3eda5541-a106-407f-b127-4df9d8740a6b
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column available
		dataType: string
		lineageTag: 96f27f1f-b01c-4abd-b69c-4a9c50b988bf
		summarizeBy: none
		sourceColumn: available

		annotation SummarizationSetBy = Automatic

	column price
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 5724562e-fa1b-439f-a915-4acf6fc857db
		summarizeBy: sum
		sourceColumn: price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	partition occupancy-a94f673b-e8aa-47ea-995d-9b3df82d3700 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\sarinas\Desktop\OneDriveLocalBackup\Hackathon18\calendar.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"listing_id", Int64.Type}, {"date", type date}, {"available", type text}, {"price", Currency.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

