table weather
	lineageTag: 38b2c205-7e5f-46f0-90bc-0a0f1a4919e0

	measure '% Rain (days)' = CALCULATE(COUNTROWS(weather),weather[RAIN]="True")/COUNTROWS(weather)
		formatString: 0
		lineageTag: e5547335-e409-4a6c-8f45-bdee8dc1a6e4

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: dc6c6bbd-c3c2-46e4-8888-2aed7131c0f2
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PRCP
		dataType: double
		lineageTag: 58f5bec6-e26d-46bd-982a-ba32b70469e3
		summarizeBy: sum
		sourceColumn: PRCP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TMAX
		dataType: int64
		formatString: 0
		lineageTag: b3204eaa-f593-49a2-bacc-1a1a44ab922a
		summarizeBy: sum
		sourceColumn: TMAX

		annotation SummarizationSetBy = Automatic

	column TMIN
		dataType: int64
		formatString: 0
		lineageTag: e5bd3f5e-0456-4eef-9fde-ed350a2c54ee
		summarizeBy: sum
		sourceColumn: TMIN

		annotation SummarizationSetBy = Automatic

	column RAIN
		dataType: string
		lineageTag: 7880097b-fd40-49df-882d-6876fdb8aaa7
		summarizeBy: none
		sourceColumn: RAIN

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	partition weather-ce6d3b36-7adc-4a71-bd23-9b8b41b541d9 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\sarinas\Desktop\OneDriveLocalBackup\Hackathon18\WeatherSeattle2005-2017.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DATE", type text}, {"PRCP", type number}, {"TMAX", Int64.Type}, {"TMIN", Int64.Type}, {"RAIN", type logical}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"DATE", "Date"}}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Renamed Columns", {"RAIN"}),
				    #"Changed Type with Locale" = Table.TransformColumnTypes(#"Removed Errors", {{"Date", type date}}, "en-150")
				in
				    #"Changed Type with Locale"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

